#ifndef H_NETWORKING_KEY
#define H_NETWORKING_KEY

#define PORT_PLAINTEXT 8080
#define PORT_VIDEO 2505

#define KILL_INIT_AFTER 2
#define INIT_WAIT_S 1

#define COMMAND_PING "PING"
#define RESPONSE_PONG "PONG"

#define PROTOCOL_AUTO 0
#define INVALID -1

#define MAX_CONNECTIONS 32
#define MSG_SIZE 1024

#define MAX_RETRIES 5
#define MAX_RETRIES_EXTENDED 1800

#endif // H_NETWORKING_KEY